# Generated by Django 6.0.5 on 2026-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0002_task_status_task_user_alter_task_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
